import Head from "next/head";
import Hero from "../../components/Hero";
import Navbar from "components/Navbar";
import Slider from "components/Slider";
import { SliderData } from "components/SliderData";
export default function Home() {
  return (
    <>
      <Head>
        <title>Blog website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero
        heading="Stanisław Świerk"
        message="Łapię wartościowe momenty i zapisuje w obrazie na zawsze"
      />
      <Slider slides={SliderData} />
    </>
  );
}
